[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true

remappings = [
    "solady/=lib/solady/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[fmt]
line_length = 120
bracket_spacing = true

[invariant]
runs = 5000
depth = 64
fail_on_revert = true

[rpc_endpoints]
amoy = "${TEST_NET_RPC_URL}"
anvil = "http://127.0.0.1:8545"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
